// TouristSafety Contract ABI - Deployed Contract
export const TOURIST_SAFETY_ABI = [
  {"inputs":[],"stateMutability":"nonpayable","type":"constructor"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"admin","type":"address"},{"indexed":false,"internalType":"address","name":"addedBy","type":"address"}],"name":"AdminAdded","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"admin","type":"address"},{"indexed":false,"internalType":"address","name":"removedBy","type":"address"}],"name":"AdminRemoved","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"alertId","type":"string"},{"indexed":false,"internalType":"address","name":"dismissedBy","type":"address"}],"name":"AlertDismissed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"zoneId","type":"string"},{"indexed":false,"internalType":"string","name":"name","type":"string"},{"indexed":false,"internalType":"int256","name":"latitude","type":"int256"},{"indexed":false,"internalType":"int256","name":"longitude","type":"int256"},{"indexed":false,"internalType":"uint256","name":"radius","type":"uint256"},{"indexed":false,"internalType":"enum TouristSafety.ZoneLevel","name":"level","type":"uint8"},{"indexed":false,"internalType":"address","name":"createdBy","type":"address"}],"name":"DangerZoneCreated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"zoneId","type":"string"},{"indexed":false,"internalType":"address","name":"removedBy","type":"address"}],"name":"DangerZoneRemoved","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"zoneId","type":"string"},{"indexed":false,"internalType":"string","name":"name","type":"string"},{"indexed":false,"internalType":"uint256","name":"radius","type":"uint256"},{"indexed":false,"internalType":"enum TouristSafety.ZoneLevel","name":"level","type":"uint8"}],"name":"DangerZoneUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"alertId","type":"string"},{"indexed":true,"internalType":"address","name":"tourist","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"EmergencyAlertCreated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"tourist","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"int256","name":"latitude","type":"int256"},{"indexed":false,"internalType":"int256","name":"longitude","type":"int256"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"LocationUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"tourist","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"enum TouristSafety.SafetyStatus","name":"oldStatus","type":"uint8"},{"indexed":false,"internalType":"enum TouristSafety.SafetyStatus","name":"newStatus","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"StatusUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"wallet","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"string","name":"username","type":"string"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"TouristRegistered","type":"event"},
  {"inputs":[{"internalType":"address","name":"_admin","type":"address"}],"name":"addAdmin","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"admins","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"alertCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"alerts","outputs":[{"internalType":"string","name":"alertId","type":"string"},{"internalType":"address","name":"tourist","type":"address"},{"internalType":"string","name":"touristId","type":"string"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"string","name":"zoneName","type":"string"},{"internalType":"enum TouristSafety.ZoneLevel","name":"zoneLevel","type":"uint8"},{"internalType":"uint256","name":"timestamp","type":"uint256"},{"internalType":"bool","name":"isDismissed","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"string","name":"_name","type":"string"},{"internalType":"int256","name":"_latitude","type":"int256"},{"internalType":"int256","name":"_longitude","type":"int256"},{"internalType":"uint256","name":"_radius","type":"uint256"},{"internalType":"enum TouristSafety.ZoneLevel","name":"_level","type":"uint8"}],"name":"createDangerZone","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"dangerZones","outputs":[{"internalType":"string","name":"zoneId","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"uint256","name":"radius","type":"uint256"},{"internalType":"enum TouristSafety.ZoneLevel","name":"level","type":"uint8"},{"internalType":"address","name":"createdBy","type":"address"},{"internalType":"uint256","name":"createdAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_alertIndex","type":"uint256"}],"name":"dismissAlert","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[],"name":"getActiveAlerts","outputs":[{"components":[{"internalType":"string","name":"alertId","type":"string"},{"internalType":"address","name":"tourist","type":"address"},{"internalType":"string","name":"touristId","type":"string"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"string","name":"zoneName","type":"string"},{"internalType":"enum TouristSafety.ZoneLevel","name":"zoneLevel","type":"uint8"},{"internalType":"uint256","name":"timestamp","type":"uint256"},{"internalType":"bool","name":"isDismissed","type":"bool"}],"internalType":"struct TouristSafety.EmergencyAlert[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getActiveDangerZones","outputs":[{"components":[{"internalType":"string","name":"zoneId","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"uint256","name":"radius","type":"uint256"},{"internalType":"enum TouristSafety.ZoneLevel","name":"level","type":"uint8"},{"internalType":"address","name":"createdBy","type":"address"},{"internalType":"uint256","name":"createdAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"}],"internalType":"struct TouristSafety.DangerZone[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getAdmins","outputs":[{"internalType":"address[]","name":"","type":"address[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getAllAlerts","outputs":[{"components":[{"internalType":"string","name":"alertId","type":"string"},{"internalType":"address","name":"tourist","type":"address"},{"internalType":"string","name":"touristId","type":"string"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"string","name":"zoneName","type":"string"},{"internalType":"enum TouristSafety.ZoneLevel","name":"zoneLevel","type":"uint8"},{"internalType":"uint256","name":"timestamp","type":"uint256"},{"internalType":"bool","name":"isDismissed","type":"bool"}],"internalType":"struct TouristSafety.EmergencyAlert[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getAllDangerZones","outputs":[{"components":[{"internalType":"string","name":"zoneId","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"uint256","name":"radius","type":"uint256"},{"internalType":"enum TouristSafety.ZoneLevel","name":"level","type":"uint8"},{"internalType":"address","name":"createdBy","type":"address"},{"internalType":"uint256","name":"createdAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"}],"internalType":"struct TouristSafety.DangerZone[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getAllTourists","outputs":[{"components":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"internalType":"struct TouristSafety.Tourist[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"_wallet","type":"address"}],"name":"getTourist","outputs":[{"components":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"internalType":"struct TouristSafety.Tourist","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"string","name":"_touristId","type":"string"}],"name":"getTouristById","outputs":[{"components":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"internalType":"struct TouristSafety.Tourist","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"getTouristCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"enum TouristSafety.SafetyStatus","name":"_status","type":"uint8"}],"name":"getTouristsByStatus","outputs":[{"components":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"internalType":"struct TouristSafety.Tourist[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"isAdmin","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"_wallet","type":"address"}],"name":"isRegistered","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"string","name":"_username","type":"string"},{"internalType":"string","name":"_email","type":"string"},{"internalType":"string","name":"_phone","type":"string"},{"internalType":"uint256","name":"_dateOfBirth","type":"uint256"}],"name":"registerTourist","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"registeredTourists","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"_admin","type":"address"}],"name":"removeAdmin","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_zoneIndex","type":"uint256"}],"name":"removeDangerZone","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"string","name":"","type":"string"}],"name":"touristIdToAddress","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"tourists","outputs":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafety.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_zoneIndex","type":"uint256"},{"internalType":"string","name":"_name","type":"string"},{"internalType":"uint256","name":"_radius","type":"uint256"},{"internalType":"enum TouristSafety.ZoneLevel","name":"_level","type":"uint8"}],"name":"updateDangerZone","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"int256","name":"_latitude","type":"int256"},{"internalType":"int256","name":"_longitude","type":"int256"}],"name":"updateLocation","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"enum TouristSafety.SafetyStatus","name":"_status","type":"uint8"}],"name":"updateStatus","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"string","name":"","type":"string"}],"name":"zoneIdToIndex","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}
] as const;

// Status enum mapping (matches contract's SafetyStatus enum)
export const TouristStatus = {
  Safe: 0,
  Alert: 1,
  Emergency: 2
} as const;

// Zone level enum mapping (matches contract's ZoneLevel enum)
export const ZoneLevel = {
  Low: 0,
  Medium: 1,
  High: 2,
  Critical: 3
} as const;

export type TouristStatusType = typeof TouristStatus[keyof typeof TouristStatus];
export type ZoneLevelType = typeof ZoneLevel[keyof typeof ZoneLevel];

// Contract addresses (update with your deployed contract address)
export const CONTRACT_ADDRESSES = {
  // Ethereum Mainnet
  mainnet: "",
  // Sepolia Testnet - UPDATE THIS WITH YOUR DEPLOYED CONTRACT ADDRESS
  sepolia: "0x02F55E421205a6Ddd78277eF74a26cc8Cb63C357",
  // Local development
  localhost: "0x02F55E421205a6Ddd78277eF74a26cc8Cb63C357",
} as const;

export type NetworkName = keyof typeof CONTRACT_ADDRESSES;

// No registration fee in this contract version
export const DEFAULT_REGISTRATION_FEE = "0";
